### PR TITLE
Pep Fixes + Speed Optimizations + Better error output

### PR DESCRIPTION
**Pull request by naemono**
Pep Fixes
Adding timeouts to all requests per http://docs.python-requests.org/en/master/user/quickstart/#timeouts
Threading the filtering of data to speed things up with many DCs, and large amounts of data
Adding output for exceptions, such as wrong user/pass, which are difficult to debug without
Adding some python3 compatible code

### CODE REVIEW

**Comment by alex-leonhardt** [comment]
Wow, thanks Michael! 

Unfortunately, I'll only be able to pull this down coming weekend earliest; will merge as soon as I had at least a go at running it locally. 

Always wanted to use threading for the filtered view too, just never got around doing it 👍 !

**Comment by naemono** [comment]
@alex-leonhardt Glad to help man.  We're using this on some pretty large datacenters, and ran into many instances where failures weren't visible, and it was quite slow.  There's still quite a lot of optimization you could do, so as calling `get_data`, `get_clients`, `get_stashes`, and `get_filter_data` in a single threadpool, as they're not dependent on each other, which will speed things up greatly when many datacenters are involved.

Nice work on this though, as it's super useful to have a high-level view.

**Comment by alex-leonhardt** [comment]
I've had a quick look this morning and tried to run the app with one of the Vagrant hosts (`vagrant1`)but I'm seeing 2 issues : 


Python:
```
Python 2.7.5
```
OS:
```
Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

CentOS Linux release 7.2.1511 (Core)
```
Python packages:
```
Flask==0.12.2
Jinja2==2.10
MarkupSafe==1.0
PyYAML==3.12
Werkzeug==0.14.1
argparse==1.4.0
certifi==2018.01.18
chardet==3.0.4
click==6.7
gunicorn==19.7.1
idna==2.6
itsdangerous==0.24
requests==2.18.4
six==1.11.0
urllib3==1.22
wsgiref==0.1.2
```

1) when going to http://localhost:5000/events/dev , I'm getting a 500 error (this is due to some unicode decoding issue : 
```
10.0.2.2 - - [26/Jan/2018 07:25:58] "GET /events/dev HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/opt/sensu-grid/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/sensu-grid/reverseproxied.py", line 32, in __call__
    return self.app(environ, start_response)
  File "/opt/sensu-grid/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/sensu-grid/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/sensu-grid/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/sensu-grid/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/sensu-grid/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/sensu-grid/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/sensu-grid/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/sensu-grid/sensugrid.py", line 155, in events
    results += get_events(dc, timeout, filters.split(','))
  File "/opt/sensu-grid/griddata.py", line 186, in get_events
    return filter(filter_events(filters), data)
  File "/opt/sensu-grid/griddata.py", line 155, in filter_event
    if filter_object(event, f):
  File "/opt/sensu-grid/griddata.py", line 140, in filter_object
    if filter_object(value, search):
  File "/opt/sensu-grid/griddata.py", line 147, in filter_object
    return six.u(search) in six.u(obj)
  File "/opt/sensu-grid/lib/python2.7/site-packages/six.py", line 653, in u
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
TypeError: decoding Unicode is not supported
```

2) when using the `Filter by` drop down, the list is that is generated is incorrect, I'm seeing
```
[u'test', u'client:localhost']
[u'test', u'client:localhost']
[u'test', u'client:localhost']
[u'test', u'client:localhost']
```
screen shot 2018-01-26 at 07 25 54

when I should see 
```
test
client:localhost
```
screen shot 2018-01-26 at 07 31 12

I'll see if I have time over the weekend to fix those and do another round of quick testing ... I should probably also update the (few) tests and add the `events view` and verifying the drop down list in some way if possible. 

Cheers!
Alex

**Comment by alex-leonhardt** [comment]
Merged w/ some fixes for the `Filter by` drop-down and the `events` view 👍 .. Thanks again @naemono !

**Pull request merged**
